# Generated by Django 3.1.3 on 2021-09-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('description', models.TextField()),
                ('therapist', models.CharField(max_length=255, verbose_name='Terapeutas')),
                ('duration', models.IntegerField(verbose_name='Duracion (Tiempo) ')),
                ('price', models.IntegerField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Terapia',
                'verbose_name_plural': 'Terapias',
            },
        ),
    ]
