# Generated by Django 3.1.3 on 2021-09-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_auto_20210913_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
    ]
